### ISSUE TITLE
Downloaden lukt niet wat gaat er fout? Database werkt wel.

### ISSUE THREAD

**Issue by PD1LOI** [DMR-Database/md380tools#1]
Als ik de link plaats werkt het niet
        // firmware
        private void DownloadGPSButton_Click(object sender, EventArgs e)
        {
            StatusLabel.Text = "downloading gps_fw.bin ...";

            downloading = true;
            webc.DownloadFileAsync(new Uri("**https://github.com/BM-Database/md380tools/raw/master/firmware-GPS.bin"), "gps_fw.bin**");

            if(File.Exists("nongps_fw.bin"))
            {
                File.Delete("nongps_fw.bin");
            }
        }

        private void DownloadNONGPSButton_Click(object sender, EventArgs e)
        {
            StatusLabel.Text = "downloading nongps_fw.bin ...";
            DLFileName = "fw.bin";
            downloading = true;
            webc.DownloadFileAsync(new Uri("https://github.com/BM-Database/md380tools/raw/master/firmware-noGPS.bin"), "nongps_fw.bin");

            if (File.Exists("gps_fw.bin"))
            {
                File.Delete("gps_fw.bin");
            }
        }

**Comment by PD1LOI** [comment]
Dit werkt ook niet,

      // firmware
        private void DownloadGPSButton_Click(object sender, EventArgs e)
        {
            StatusLabel.Text = "downloading gps_fw.bin ...";

            downloading = true;
            webc.DownloadFileAsync(new Uri("https://github.com/BM-Database/md380tools/blob/master/firmware-GPS.bin?raw=true"), "gps_fw.bin");

            if(File.Exists("nongps_fw.bin"))
            {
                File.Delete("nongps_fw.bin");
            }
        }

        private void DownloadNONGPSButton_Click(object sender, EventArgs e)
        {
            StatusLabel.Text = "downloading nongps_fw.bin ...";
            DLFileName = "fw.bin";
            downloading = true;
            webc.DownloadFileAsync(new Uri("https://github.com/BM-Database/md380tools/blob/master/firmware-noGPS.bin?raw=true"), "nongps_fw.bin");

            if (File.Exists("gps_fw.bin"))
            {
                File.Delete("gps_fw.bin");
            }
        }

**Comment by javastraat** [comment]
goed link is
https://github.com/BM-Database/md380tools/raw/master/firmware-noGPS.bin etc etc


________________________________
Van: L Kuperij <notifications@github.com>
Verzonden: dinsdag 2 juli 2019 05:42
Aan: BM-Database/md380tools
CC: Subscribed
Onderwerp: Re: [BM-Database/md380tools] Downloaden lukt niet wat gaat er fout? Database werkt wel. (#1)


Dit werkt ook niet,

  // firmware
    private void DownloadGPSButton_Click(object sender, EventArgs e)
    {
        StatusLabel.Text = "downloading gps_fw.bin ...";

        downloading = true;
        webc.DownloadFileAsync(new Uri("https://github.com/BM-Database/md380tools/blob/master/firmware-GPS.bin?raw=true"), "gps_fw.bin");

        if(File.Exists("nongps_fw.bin"))
        {
            File.Delete("nongps_fw.bin");
        }
    }

    private void DownloadNONGPSButton_Click(object sender, EventArgs e)
    {
        StatusLabel.Text = "downloading nongps_fw.bin ...";
        DLFileName = "fw.bin";
        downloading = true;
        webc.DownloadFileAsync(new Uri("https://github.com/BM-Database/md380tools/blob/master/firmware-noGPS.bin?raw=true"), "nongps_fw.bin");

        if (File.Exists("gps_fw.bin"))
        {
            File.Delete("gps_fw.bin");
        }
    }

**Comment by javastraat** [comment]
opgelost in 2.0 werkt :)
